# XNovu Test Environment Docker Compose
#
# Sets up services needed for running integration tests.
# Temporal is configured as an external service or mocked in tests.

version: '3.8'

services:
  # Test PostgreSQL Database
  postgres-test:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: xnovu_test
    ports:
      - "54322:5432"
    volumes:
      - ./docker/init-test.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data

  # Supabase for testing (optional)
  # Uncomment if you need a full Supabase instance for tests
  # supabase-test:
  #   image: supabase/postgres:15.1.0.117
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "54321:5432"

# Note: Temporal can be mocked in unit tests or run as a separate service for integration tests