# XNovu Development Docker Compose
# 
# This file sets up the development environment for XNovu.
# Temporal is configured as an external service via environment variables.

version: '3.8'

services:
  # Development PostgreSQL for local testing (optional)
  # Uncomment if you want to run a local Supabase instance
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: xnovu
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

  # Add other development services as needed
  # For example: local email server, monitoring tools, etc.

volumes:
  postgres_data: