name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  # Lint, build, and connection tests
  lint-build-connection:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        registry-url: 'http://172.20.60.129:4873'

    - name: Configure pnpm registry
      run: pnpm config set registry http://172.20.60.129:4873

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Temporal CLI
      uses: temporalio/setup-temporal@v0

    - name: Start local Temporal server
      shell: bash
      run: |
        PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()")
        temporal server start-dev --headless --port $PORT &
        echo "TEMPORAL_ADDRESS=localhost:$PORT" >> $GITHUB_ENV

    - name: Run linter
      run: pnpm lint

    - name: Run type check and build
      run: pnpm build
      env:
        NOVU_SECRET_KEY: ${{ secrets.NOVU_SECRET_KEY }}
        NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER }}
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        TEMPORAL_ADDRESS: ${{ env.TEMPORAL_ADDRESS }}
        TEMPORAL_NAMESPACE: default
        TEMPORAL_TASK_QUEUE: ${{ secrets.TEMPORAL_TASK_QUEUE }}

    - name: Run connection tests
      run: pnpm test:connection
      env:
        CI: true
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NOVU_SECRET_KEY: ${{ secrets.NOVU_SECRET_KEY }}
        NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER }}
        TEMPORAL_ADDRESS: ${{ env.TEMPORAL_ADDRESS }}
        TEMPORAL_NAMESPACE: default
        TEMPORAL_TASK_QUEUE: ${{ secrets.TEMPORAL_TASK_QUEUE }}

  # Unit tests
  test-unit:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        registry-url: 'http://172.20.60.129:4873'

    - name: Configure pnpm registry
      run: pnpm config set registry http://172.20.60.129:4873

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Temporal CLI
      uses: temporalio/setup-temporal@v0

    - name: Start local Temporal server
      shell: bash
      run: |
        PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()")
        temporal server start-dev --headless --port $PORT &
        echo "TEMPORAL_ADDRESS=localhost:$PORT" >> $GITHUB_ENV

    - name: Run unit tests
      run: pnpm test:unit
      env:
        CI: true
        NODE_ENV: test
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NOVU_SECRET_KEY: ${{ secrets.NOVU_SECRET_KEY }}
        NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER }}
        TEMPORAL_ADDRESS: ${{ env.TEMPORAL_ADDRESS }}
        TEMPORAL_NAMESPACE: default
        TEMPORAL_TASK_QUEUE: ${{ secrets.TEMPORAL_TASK_QUEUE }}

    - name: Upload unit test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: unit-test-results
        path: |
          coverage/unit/
          junit-unit.xml
        retention-days: 7

  # Integration tests
  test-integration:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        registry-url: 'http://172.20.60.129:4873'

    - name: Configure pnpm registry
      run: pnpm config set registry http://172.20.60.129:4873

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Install Temporal CLI
      uses: temporalio/setup-temporal@v0

    - name: Start local Temporal server
      shell: bash
      run: |
        PORT=$(python3 -c "import socket; s=socket.socket(); s.bind(('',0)); print(s.getsockname()[1]); s.close()")
        temporal server start-dev --headless --port $PORT &
        echo "TEMPORAL_ADDRESS=localhost:$PORT" >> $GITHUB_ENV

    - name: Run integration tests
      run: pnpm test:integration
      env:
        CI: true
        NODE_ENV: test
        NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        NOVU_SECRET_KEY: ${{ secrets.NOVU_SECRET_KEY }}
        NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER: ${{ secrets.NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER }}
        TEMPORAL_ADDRESS: ${{ env.TEMPORAL_ADDRESS }}
        TEMPORAL_NAMESPACE: default
        TEMPORAL_TASK_QUEUE: ${{ secrets.TEMPORAL_TASK_QUEUE }}

    - name: Upload integration test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: integration-test-results
        path: |
          coverage/integration/
          junit-integration.xml
        retention-days: 7

